### ISSUE TITLE
Question about performance

### ISSUE THREAD

**Issue by stepanho** [adrianhajdin/tutorial_currency_converter#1]
If getExchangeRate executes during X ms and getCountries executes during Y ms, how long time convertCurrency will take? (X+Y) or (max(X,Y)) ?
If first, Is it possible to reach second one?

Thank you.

**Comment by adrianhajdin** [comment]
Sorry for the late reply. That's a great question.
If we fetch data from each separate API, and use await on each one, the program will take (X+Y).
As you figured (congrats on that!), it is possible to reach max(X,Y) by using Promise.all(). 

The code is now updated and features the latter. You can take a look. 
Cheers and thank you.
