### ISSUE TITLE
Code here doesn't match video

### ISSUE THREAD

**Issue by kahunacoder** [adrianhajdin/tutorial_currency_converter#2]
I like your article and video. They cleared up a lot of confusion around aysnc/await and promises. 

The video code is different then the code here. In particular the getExchangeRate function here doesn't have the isNaN throw error block. Instead it has a try/catch block. 

It would be helpful to see how you would integrate the two error catching methods in that one function.

**Comment by adrianhajdin** [comment]
Greetings, glad you like the tutorials. 

These are just two different ways to catch and output errors.

Cheers.
